<html>
<head>
    <title>MVC</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="../css/bootstrap.css">
    <script src="../js/jquery-3.1.1.slim.min.js"></script>
    <script src="../js/tether.min.js"></script>
    <script src="../js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="margin-bottom: 30px">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">Início</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Criar
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="/inserir-usuario">Inserir Usuario</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    <div class="row-fluid">
        <form action="" method="POST">
            <div class="form-group">
                <input type="text" class="form-control" maxlength="100" placeholder="Nome" name="nome" required>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" maxlength="100" placeholder="Email" name="email" required>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" maxlength="100" placeholder="Senha" name="senha" required>
            </div>
            <button class="btn btn-primary">Enviar</button>
        </form>
    </div>
</div>

</body>
</html>
